version: "3.9"

services:
  database:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=piazza-clone
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
